trainingbook/views/exercise.py
__author__ = 'elwood'

from flask import Blueprint, request, redirect, render_template, url_for, abort
from flask.ext.mongoengine.wtf import model_form
from trainingbook.models import Exercise

mod = Blueprint('exercises', __name__, url_prefix='/exercises', template_folder='templates')

@mod.route('/')
def index():
     exercises = Exercise.objects.all()
     return render_template('exercises/list.html', exercises=exercises)

@mod.route('/delete/<id>')
def delete(id):
    exercise = Exercise.objects.get_or_404(id=id)
    exercise.delete()
    return redirect(url_for('exercises.index'))

@mod.route('/add', methods=['GET', 'POST'])
def add():
    return get_page()

@mod.route('/edit/<id>', methods=['GET', 'POST'])
def edit(id):
    return get_page(id)

def get_page(id=None):
    context = get_context(id)

    if request.method == 'POST':
        form = context.get('form')
        if form.validate():
            exercise = context.get('exercise')
            form.populate_obj(exercise)
            exercise.save()
            return redirect(url_for('exercises.index'))
    return render_template('exercises/edit.html', **context)

def get_context(id=None):
    if id:
        # edit
        exercise = Exercise.objects.get_or_404(id=id)
        form_cls = model_form(exercise.__class__)

        if request.method == 'POST':
            form = form_cls(request.form, inital=exercise._data)
            # process single line list
            for muscle in filter(None, request.form['muscles'].split('\r\n')):
                form.muscles.append_entry(muscle)
        else:
            form = form_cls(obj=exercise)
    else:
        # create
        exercise = Exercise()
        form_cls = model_form(exercise.__class__)
        form = form_cls(request.form)
        # process single line list
        if 'muscles' in request.form:
            for muscle in filter(None, request.form['muscles'].split('\r\n')):
                form.muscles.append_entry(muscle)

    context = {
            "exercise": exercise,
            "form": form,
            "create": id is None
        }
    return context

trainingbook/templates/exercises/edit.html
{% extends "base.html" %}
{% import 'forms.html' as forms %}
{% set active_page = "exercises" %}

{% block page_header %}
    <h1>Edit Exercise</h1>
{% endblock %}

{% block content %}
<form class="form-horizontal" method="post" action="?{{ request.query_string }}">
    <fieldset>
    {{ forms.render(form) }}
    <div class="form-group">
        <div class="col-xs-offset-2 col-xs-10">
            <button type="submit" class="btn btn-primary">Save</button>
            <a href="{{ url_for('exercises.index') }}" class="btn btn-default">Cancel</a>
        </div>
    </div>
</form>
{% endblock %}

trainingbook/templates/exercises/list.html
{% extends "base.html" %}
{% set active_page = "exercises" %}

{% block page_header %}
    <h1>
        Exercises
        <a href="{{ url_for('exercises.add') }}">
            <button class="btn btn-primary btn-large">
            <i class="fa fa-plus-circle"></i></button>
        </a>
    </h1>
{% endblock %}

{% block content %}
    <table class="table table-hover table-condensed">
        <thead>
            <th>Name</th>
            <th>Muscles</th>
            <th>Description</th>
            <th></th>
        </thead>
        <tbody>
            {% for exercise in exercises %}
                <tr>
                    <td>{{ exercise.name }}</td>
                    <td>
                        {% if exercise.muscles %}
                            <ul>
                            {% for muscle in exercise.muscles %}
                                <li>{{ muscle }}</li>
                            {% endfor %}
                            </ul>
                        {% endif %}
                    </td>
                    <td>{% if exercise.description %}{{ exercise.description }}{% endif %}</td>
                    <td>
                        <a href="{{ url_for('exercises.edit', id=exercise.id) }}">
                            <button class="btn btn-primary"><i class="fa fa-pencil"></i></button>
                        </a>
                        <a class="confirmLink" href="{{ url_for('exercises.delete', id=exercise.id) }}">
                            <button class="btn btn-danger"><i class="fa fa-trash-o"></i></button>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <div id="dialog" title="Confirmation Required">Are you sure about this?</div>
{% endblock %}

{% block js_footer %}
    <script type="text/javascript">
        $(document).ready(function () {
            $("#dialog").dialog({
                autoOpen: false,
                modal: true
            });
        });

        $(".confirmLink").click(function (e) {
            e.preventDefault();
            var targetUrl = $(this).attr("href");

            $("#dialog").dialog({
                buttons: {
                    "Confirm": function () {
                        window.location.href = targetUrl;
                    },
                    "Cancel": function () {
                        $(this).dialog("close");
                    }
                }
            });

            $("#dialog").dialog("open");
        });
    </script>
{% endblock %}