trainingbook/views/cycle.py
__author__ = 'elwood'

from flask import Blueprint, request, redirect, render_template, url_for, abort
from flask.ext.mongoengine.wtf import model_form
from trainingbook.models import Exercise, Cycle, Set, WeightedSet, PlannedExercise
import operator

mod = Blueprint('cycles', __name__, url_prefix='/cycles', template_folder='templates')

@mod.route('/')
def index():
    cycles = Cycle.objects.all()
    for cycle in cycles:
        cycle.exercises.sort(key=operator.attrgetter('position'))
    return render_template('cycles/list.html', cycles=cycles)

@mod.route('/add', methods=['GET', 'POST'])
def add():
    return get_page()

@mod.route('/edit/<id>', methods=['GET', 'POST'])
def edit(id):
    return get_page(id)

@mod.route('/delete/<id>')
def delete(id):
    cycle = Cycle.objects.get_or_404(id=id)
    cycle.delete()
    return redirect(url_for('cycles.index'))


@mod.route('/test', methods=['GET'])
def get_page(id=None):
    context = get_context(id)

    if request.method == 'POST':
        cycle = context.get("cycle")
        update_cycle(cycle)
        cycle.save()
        return redirect(url_for('cycles.index'))

    return render_template('cycles/edit.html', **context)

def update_cycle(cycle):
    form = request.form

    # update name
    cycle.name = form["name"]

    # add new exercise(s)
    exercise_counter = len(cycle.exercises) + 1
    form_exercise = "exercise-{0}".format(exercise_counter)
    while form_exercise in form:
        actual_exercise = Exercise.objects.get(id=form[form_exercise])
        new_exercise = PlannedExercise(
            position = exercise_counter,
            exercise = actual_exercise,
            sets = []
        )
        cycle.exercises.append(new_exercise)

        exercise_counter += 1
        form_exercise = "exercise-{0}".format(exercise_counter)

    # update sets
    for i in range(len(cycle.exercises)):
        ex = cycle.exercises[i]
        set_counter = 1
        use_weight = ex.exercise.use_weight

        form_reps = "set-{0}-{1}-reps".format(i+1, set_counter)

        while form_reps in form:
            form_weight = "set-{0}-{1}-weight".format(i+1, set_counter)

            if len(ex.sets) >= set_counter:
                # update set
                ex.sets[set_counter-1].repetitions = form[form_reps]
                if use_weight:
                    ex.sets[set_counter-1].weight = form[form_weight]
            else:
                # add new set
                if use_weight:
                    new_set = WeightedSet(
                        repetitions = form[form_reps],
                        weight = form[form_weight])
                else:
                    new_set = Set(repetitions = form[form_reps])
                ex.sets.append(new_set)

            set_counter += 1
            form_reps = "set-{0}-{1}-reps".format(i+1, set_counter)

    # reorder exercises
    if form["order"]:
        order = [int(x) for x in form["order"][:-1].split(",")]
        cycle.exercises = [cycle.exercises[i-1] for i in order]

        # set new position
        for i in range(len(cycle.exercises)):
            cycle.exercises[i].position = i + 1

def get_context(id=None):
    exercises = Exercise.objects.all()

    if id:
        # edit
        cycle = Cycle.objects.get_or_404(id=id)
        cycle.exercises.sort(key=operator.attrgetter('position'))
    else:
        # create
        cycle = Cycle()

    context = {
            "cycle": cycle,
            "exercises": exercises,
            "create": id is None
        }
    return context

trainingbook/views/workout.py
__author__ = 'elwood'

from flask import Blueprint, request, redirect, render_template, url_for, abort
from flask.ext.mongoengine.wtf import model_form
from trainingbook.models import Exercise, Cycle, Set, WeightedSet, PlannedExercise, Workout, PerformedExercise
import operator

mod = Blueprint('workouts', __name__, url_prefix='/workouts', template_folder='templates')

@mod.route('/')
def index():
    workouts = Workout.objects.all()
    return render_template('workouts/list.html', workouts=workouts)

@mod.route('/add', methods=['GET', 'POST'])
def add():
    cycles = Cycle.objects.all()
    return render_template('workouts/start.html', cycles=cycles)

@mod.route('/fill/<cycle_id>', methods=['GET', 'POST'])
@mod.route('/fill/<cycle_id>/<id>', methods=['GET', 'POST'])
@mod.route('/fill/<cycle_id>/<id>/<int:position>', methods=['GET', 'POST'])
def fill(cycle_id, id=None, position=0):
    cycle = Cycle.objects.get_or_404(id=cycle_id)
    if id:
        workout = Workout.objects.get_or_404(id=id)
    else:
        workout = Workout(cycle=cycle)
        for planned_exercise in cycle.exercises:
            new_exercise = PerformedExercise(exercise=planned_exercise.exercise, sets=[])
            workout.exercises.append(new_exercise)
        workout.save()
        return redirect(url_for('workouts.fill', cycle_id=cycle.id, id=workout.id))

    # TODO: save input if needed

    if position < len(cycle.exercises):
        # render n-th exercise input
        return render_template('workouts/input.html', workout=workout, position=position)
    else:
        # render summary
        return render_template('workouts/summary.html', workout=workout)

@mod.route('/view/<id>', methods=['GET'])
def view(id):
    abort(404)

@mod.route('/edit/<id>', methods=['GET', 'POST'])
def edit(id=None):
    abort(404)

trainingbook/templates/workouts/input.html
{% extends "base.html" %}
{% set active_page = "workouts" %}
{% set exercise = workout.exercises[position].exercise %}
{% set performed = workout.exercises[position] %}

{% block page_header %}
    <h1>'{{ workout.cycle.name }}' <small id="exercise"{% if exercise.use_weight %} class="weight"{% endif %}>{{ exercise.name }} ({{ position+1 }})</small></h1>
{% endblock %}

{% block content %}
    <table id="sets" class="table table-hover sets">
      <thead>
        <th>Repetitions</th>
        {% if exercise.use_weight %}<th>Weight (kg)</th>{% endif %}
        <th><button title="Add Set" class="btn btn-primary btn-xs addset"><i class="fa fa-plus-circle"></i> Add Set</button></th>
      </thead>
      <tbody>
        {% for set in performed.sets %}
            <tr>
              <td><input type="number" class="form-control" value="12" required name="set-{{ loop.index }}-reps"></td>
              {% if exercise.use_weight %}<td><input type="number" step="any" class="form-control" value="10" required name="set-{{ loop.index }}-weight"></td>{% endif %}
              <td><button title="Remove Set" class="btn btn-danger btn-small removeset"><i class="fa fa-trash-o"></i></button><td>
            </tr>
        {% endfor %}
      </tbody>
    </table>
    <a href="{{ url_for('workouts.fill', id=workout.id, cycle_id=workout.cycle.id, position=position+1) }}">
        <button title="Save and next" class="btn btn-primary">
            {% if position+1 < workout.exercises|length %}Next{% else %}End{% endif %}
            <i class="fa fa-{% if position+1 < workout.exercises|length %}arrow-right{% else %}check{% endif %}"></i>
        </button>
    </a>
{% endblock %}

{% block js_footer%}
    <script type="text/javascript">
      function getNewSetRow(weight, setNumber) {
        var columns = '<td><input type="number" class="form-control" required name="set-' + setNumber + '-reps"></td>';
        if (weight) {
          columns += '<td><input type="number" step="any" class="form-control" required name="set-' + setNumber + '-weight"></td>';
        }
        columns += '<td><button title="Remove Set" class="btn btn-danger btn-small removeset"><i class="fa fa-trash-o"></i></button><td>';
        return '<tr>' + columns + '</tr>';
      }

      $(document).ready(function() {
        $("#sets").on("click", "button.addset", function(e) {
          e.preventDefault();

          var setTable = $("#sets");
          var setNumber = (setTable.find("tr")).size();

          var weight = $("#exercise").hasClass("weight");

          var newRow = $(getNewSetRow(weight, setNumber));
          newRow.hide();
          setTable.find('tr:last').after(newRow);
          newRow.fadeIn(250);
        });

        $("#sets").on("click", "button.removeset", function(e) {
          e.preventDefault();
          var row = $(this).closest("tr");
          row.fadeOut(250, function() {
            row.remove();
          });
        });
      });
    </script>
{% endblock %}

trainingbook/templates/workouts/list.html
{% extends "base.html" %}
{% set active_page = "workouts" %}

{% block page_header %}
        <h1>
        Workouts
        <a href="{{ url_for('workouts.add') }}">
            <button class="btn btn-primary btn-large">
            <i class="fa fa-plus-circle"></i></button>
        </a>
    </h1>
{% endblock %}

{% block content %}
    <table class="table table-hover table-condensed">
        <thead>
            <th>Date</th>
            <th>Cycle</th>
            <th>Duration</th>
            <th>Motivation</th>
            <th></th>
        </thead>
        <tbody>
            {% if workouts %}
                {% for workout in workouts %}
                <tr>
                    <td>{{ workout.timestamp }}</td>
                    <td>
                        <a href="{{ url_for('cycles.edit', id=workout.cycle.id) }}">
                            <button class="btn btn-info btn-xs"><i class="fa fa-eye"></i></button>
                        </a> {{ workout.cycle.name }}
                    </td>
                    <td>{{ workout.duration }}</td>
                    <td>{{ workout.motivation }}</td>
                    <td>
                        <a href="{{ url_for('workouts.view', id=workout.id) }}">
                            <button class="btn btn-primary"><i class="fa fa-eye"></i></button>
                        </a>
                        <a href="{{ url_for('workouts.fill', id=workout.id, cycle_id=workout.cycle.id, position=0) }}">
                            <button class="btn btn-primary"><i class="fa fa-pencil"></i></button>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="4">No workouts found</td>
                </tr>
            {% endif %}
        </tbody>
    </table>
{% endblock %}

trainingbook/templates/workouts/start.html
{% extends "base.html" %}
{% set active_page = "workouts" %}

{% block page_header %}
    <h1>
        Select cycle
    </h1>
{% endblock %}

{% block content %}
    <table class="table table-hover table-condensed">
        <thead>
            <th>Name</th>
            <th>Exercises</th>
            <th></th>
        </thead>
        <tbody>
            {% for cycle in cycles %}
                <tr>
                    <td>{{ cycle.name }}</td>
                    <td>
                        {% if cycle.exercises %}
                            <ul>
                            {% for exercise in cycle.exercises %}
                                <li>{{ exercise }}</li>
                            {% endfor %}
                            </ul>
                        {% endif %}
                    </td>
                    <td>
                        <a href="{{ url_for('workouts.fill', cycle_id=cycle.id) }}">
                            <button class="btn btn-primary"><i class="fa fa-arrow-right"></i></button>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <div id="dialog" title="Confirmation Required">Are you sure about this?</div>
{% endblock %}

{% block js_footer %}
    <script type="text/javascript">
        $(document).ready(function () {
            $("#dialog").dialog({
                autoOpen: false,
                modal: true
            });
        });

        $(".confirmLink").click(function (e) {
            e.preventDefault();
            var targetUrl = $(this).attr("href");

            $("#dialog").dialog({
                buttons: {
                    "Confirm": function () {
                        window.location.href = targetUrl;
                    },
                    "Cancel": function () {
                        $(this).dialog("close");
                    }
                }
            });

            $("#dialog").dialog("open");
        });
    </script>
{% endblock %}

trainingbook/templates/workouts/summary.html
{% extends "base.html" %}
{% set active_page = "workouts" %}

{% block page_header %}
    <h1>Summary <small>'{{ workout.cycle.name }}' @ {{ workout.timestamp }}</small></h1>
{% endblock %}

{% block content %}

{% endblock %}