trainingbook/views/cycles.py
__author__ = 'elwood'

from flask import Blueprint, request, redirect, render_template, url_for, abort
from flask.ext.mongoengine.wtf import model_form
from trainingbook.models import Exercise, Cycle

mod = Blueprint('cycles', __name__, url_prefix='/cycles', template_folder='templates')

@mod.route('/')
def index():
    abort(404)

@mod.route('/add', methods=['GET', 'POST'])
def add():
    abort(404)

@mod.route('/edit/<id>', methods=['GET', 'POST'])
def edit(id):
    abort(404)

@mod.route('/delete/<id>')
def delete(id):
    abort(404)

trainingbook/views/workout.py
__author__ = 'elwood'

from flask import Blueprint, request, redirect, render_template, url_for, abort
from flask.ext.mongoengine.wtf import model_form
from trainingbook.models import Exercise, Cycle, Set, WeightedSet, PlannedExercise, Workout, PerformedExercise
import operator

mod = Blueprint('workouts', __name__, url_prefix='/workouts', template_folder='templates')

@mod.route('/')
def index():
    workouts = Workout.objects.all()
    return render_template('workouts/list.html', workouts=workouts)

@mod.route('/add', methods=['GET', 'POST'])
def add():
    cycles = Cycle.objects.all()
    return render_template('workouts/start.html', cycles=cycles)

@mod.route('/fill/<cycle_id>', methods=['GET', 'POST'])
@mod.route('/fill/<cycle_id>/<id>', methods=['GET', 'POST'])
@mod.route('/fill/<cycle_id>/<id>/<int:position>', methods=['GET', 'POST'])
def fill(cycle_id, id=None, position=0):
    cycle = Cycle.objects.get_or_404(id=cycle_id)
    if id:
        workout = Workout.objects.get_or_404(id=id)
    else:
        workout = Workout(cycle=cycle)
        for planned_exercise in cycle.exercises:
            new_exercise = PerformedExercise(exercise=planned_exercise.exercise, sets=[])
            workout.exercises.append(new_exercise)
        workout.save()
        return redirect(url_for('workouts.fill', cycle_id=cycle.id, id=workout.id))

    # TODO: save input if needed

    if position < len(cycle.exercises):
        # render n-th exercise input
        return render_template('workouts/input.html', workout=workout, position=position)
    else:
        # render summary
        return render_template('workouts/summary.html', workout=workout)

@mod.route('/view/<id>', methods=['GET'])
def view(id):
    abort(404)

@mod.route('/edit/<id>', methods=['GET', 'POST'])
def edit(id=None):
    abort(404)

trainingbook/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>My Training Book</title>
    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.0.1/css/bootstrap.css" rel="stylesheet">
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.2/css/font-awesome.min.css" rel="stylesheet">
    <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/smoothness/jquery-ui.min.css" rel="stylesheet">
    <style>.content {padding-top: 50px;} a.brand {color: #fff } option:disabled { background:#dddddd; }</style>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.1/js/bootstrap.js"></script>
  </head>

  <body>
    {%- block topbar -%}
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">My Training Book <small>Starring Flask, MongoDB and MongoEngine</small></a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li {% if active_page == 'workouts' %}class="active"{% endif %}><a href="{{ url_for('workouts.index') }}">Workouts</a></li>
            <li {% if active_page == 'cycles' %}class="active"{% endif %}><a href="{{ url_for('cycles.index') }}">Cycles</a></li>
            <li {% if active_page == 'exercises' %}class="active"{% endif %}><a href="{{ url_for('exercises.index') }}">Exercises</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    {%- endblock -%}

    <div class="container">
      <div class="content">
        {% block page_header %}{% endblock %}
        {% block content %}{% endblock %}
      </div>
    </div>
    {% block js_footer %}{% endblock %}
  </body>
</html>

trainingbook/templates/forms.html
{% macro render(form) -%}
    <fieldset>
    {% for field in form %}
        {% if field.type in ['CSRFTokenField', 'HiddenField'] %}
            {{ field() }}
        {% else %}
            {# {{ field() }} #}
            <div class="form-group {% if field.errors %}has-error{% endif %}">
                <label for="{{ field.name }}" class="col-xs-2 control-label" style="text-transform:capitalize;">{{ field.name|replace("_", " ") }}</label>
                <div class="col-xs-10">
                    {# <span>{{field.type}}</span> #}
                    {% if field.type == 'FieldList' %}
                        {{ render_fieldlist(field) }}
                    {% elif field.type == 'ModelSelectMultipleField' %}
                        {{ render_multi_select(field) }}
                    {% elif field.type == 'StringField' %}
                        {{ render_text(field) }}
                    {% elif field.type == 'BooleanField' %}
                        {{ render_checkbox(field) }}
                    {% else %}
                        {{ field() }}
                    {% endif %}
                    {% if field.errors %}
                        <span class="help-block">{{ field.errors|join(" ")}}</span>
                    {% endif %}
                </div>
            </div>
        {% endif %}
    {% endfor %}
    </fieldset>
{% endmacro %}

{% macro render_multi_select(field) -%}
<select multiple class="form-control" id="{{ field.name }}" name="{{ field.name }}">
    {% for item in field.queryset %}
        <option {% if item in field.data %}selected{% endif %} value="{{ item.id }}">{{ item }}</option>
    {% endfor %}
</select>
{% endmacro %}

{% macro render_text(field) -%}
<input type="text" class="form-control" name="{{ field.name }}" id="{{ field.name }}"
   {% if field.object_data %}value="{{ field.object_data }}"{% endif %} placeholder="Enter {{ field.name }}">
{% endmacro %}

{% macro render_checkbox(field) -%}
<div class="checkbox">
    <label>
        <input type="checkbox" name="{{ field.name }}" id="{{ field.name }}" value="y"
                {% if field.object_data %}checked="checked"{% endif %}>
    </label>
</div>
{% endmacro %}

{% macro render_fieldlist(field) -%}
    {% if field.object_data and field.object_data[0].type == 'PlannedExercise' %}
         {{ render_planned_exercise(field) }}
    {% else %}
        {# {{ field() }} #}
        <textarea id="{{ field.name }}" name="{{ field.name }}" class="form-control" rows="5" cols="30"
               placeholder="Enter data list (one per line)">{{ field.object_data|join('\n') }}</textarea>
    {% endif %}
{% endmacro %}

{% macro render_planned_exercise(field) -%}
    <span>{{ field.data }}</span><br/>
    <table>
    {% for item in field.data %}
        <tr>
        {# render single planned exercise #}
            <td>
                <div class="controls form-inline">
                    <label for="{{item}}_position">Position</label>
                    <input type="text" class="input-small" id="{{item}}_position" placeholder="Enter position"
                            {% if item.position %}value="{{ item.position }}"{% endif %}>
                </div>
            </td>
            <td>Exercisepicker here</td>
            <td>
                <div class="controls form-inline">
                    <label for="exampleInputEmail2">Email address</label>
                    <input type="email" class="input-small" id="exampleInputEmail2" placeholder="Enter email">
                    <label for="exampleInputEmail2">Email address</label>
                    <input type="email" class="input-small" id="exampleInputEmail2" placeholder="Enter email">
                </div>
            </td>
        </tr>
    {% endfor%}
    </table>
{% endmacro %}