trainingbook/views/cycle.py
__author__ = 'elwood'

from flask import Blueprint, request, redirect, render_template, url_for, abort
from flask.ext.mongoengine.wtf import model_form
from trainingbook.models import Exercise, Cycle, Set, WeightedSet, PlannedExercise
import operator

mod = Blueprint('cycles', __name__, url_prefix='/cycles', template_folder='templates')

@mod.route('/')
def index():
    cycles = Cycle.objects.all()
    for cycle in cycles:
        cycle.exercises.sort(key=operator.attrgetter('position'))
    return render_template('cycles/list.html', cycles=cycles)

@mod.route('/add', methods=['GET', 'POST'])
def add():
    return get_page()

@mod.route('/edit/<id>', methods=['GET', 'POST'])
def edit(id):
    return get_page(id)

@mod.route('/delete/<id>')
def delete(id):
    cycle = Cycle.objects.get_or_404(id=id)
    cycle.delete()
    return redirect(url_for('cycles.index'))


@mod.route('/test', methods=['GET'])
def get_page(id=None):
    context = get_context(id)

    if request.method == 'POST':
        cycle = context.get("cycle")
        update_cycle(cycle)
        cycle.save()
        return redirect(url_for('cycles.index'))

    return render_template('cycles/edit.html', **context)

def update_cycle(cycle):
    form = request.form

    # update name
    cycle.name = form["name"]

    # add new exercise(s)
    exercise_counter = len(cycle.exercises) + 1
    form_exercise = "exercise-{0}".format(exercise_counter)
    while form_exercise in form:
        actual_exercise = Exercise.objects.get(id=form[form_exercise])
        new_exercise = PlannedExercise(
            position = exercise_counter,
            exercise = actual_exercise,
            sets = []
        )
        cycle.exercises.append(new_exercise)

        exercise_counter += 1
        form_exercise = "exercise-{0}".format(exercise_counter)

    # update sets
    for i in range(len(cycle.exercises)):
        ex = cycle.exercises[i]
        set_counter = 1
        use_weight = ex.exercise.use_weight

        form_reps = "set-{0}-{1}-reps".format(i+1, set_counter)

        while form_reps in form:
            form_weight = "set-{0}-{1}-weight".format(i+1, set_counter)

            if len(ex.sets) >= set_counter:
                # update set
                ex.sets[set_counter-1].repetitions = form[form_reps]
                if use_weight:
                    ex.sets[set_counter-1].weight = form[form_weight]
            else:
                # add new set
                if use_weight:
                    new_set = WeightedSet(
                        repetitions = form[form_reps],
                        weight = form[form_weight])
                else:
                    new_set = Set(repetitions = form[form_reps])
                ex.sets.append(new_set)

            set_counter += 1
            form_reps = "set-{0}-{1}-reps".format(i+1, set_counter)

    # reorder exercises
    if form["order"]:
        order = [int(x) for x in form["order"][:-1].split(",")]
        cycle.exercises = [cycle.exercises[i-1] for i in order]

        # set new position
        for i in range(len(cycle.exercises)):
            cycle.exercises[i].position = i + 1

def get_context(id=None):
    exercises = Exercise.objects.all()

    if id:
        # edit
        cycle = Cycle.objects.get_or_404(id=id)
        cycle.exercises.sort(key=operator.attrgetter('position'))
    else:
        # create
        cycle = Cycle()

    context = {
            "cycle": cycle,
            "exercises": exercises,
            "create": id is None
        }
    return context

trainingbook/views/cycles.py
__author__ = 'elwood'

from flask import Blueprint, request, redirect, render_template, url_for, abort
from flask.ext.mongoengine.wtf import model_form
from trainingbook.models import Exercise, Cycle

mod = Blueprint('cycles', __name__, url_prefix='/cycles', template_folder='templates')

@mod.route('/')
def index():
    abort(404)

@mod.route('/add', methods=['GET', 'POST'])
def add():
    abort(404)

@mod.route('/edit/<id>', methods=['GET', 'POST'])
def edit(id):
    abort(404)

@mod.route('/delete/<id>')
def delete(id):
    abort(404)

trainingbook/templates/cycles/edit.html
{% extends "base.html" %}
{% import 'forms.html' as forms %}
{% set active_page = "cycles" %}

{% block page_header %}
    <h1>Edit Cycle</h1>
{% endblock %}

{% macro generate_options(exercises, selected=None) -%}
    {% for exercise in exercises %}
        <option {% if selected %}{% if selected.id == exercise.id %}selected="selected"{% else %}disabled="disabled"{% endif %}{% endif %}
                value="{{ exercise.id }}" {% if exercise.use_weight %}class="weight"{% endif %}>{{ exercise.name }}</option>
    {% endfor %}
{% endmacro %}

{% block content %}
<div style="display: none;" id="excount">{{ cycle.exercises|count }}</div>
<form class="form-horizontal" role="form" method="post">
  <div class="form-group">
    <label for="inputName" class="col-xs-2 control-label">Name</label>
    <div class="col-xs-10">
      <input type="text" class="form-control" id="inputName" name="name" placeholder="Enter Name" value="{% if cycle.name %}{{ cycle.name }}{% endif %}" required>
    </div>
  </div>
  <div class="form-group">
    <label for="inputExercises" class="col-xs-2 control-label">Exercises</label>
    <div class="col-xs-10">
      <!-- show some kind of table here -->
      <div class="row">
        <div class="col-xs-3">
          <select id="newexercise" class="form-control">
            {{ generate_options(exercises) }}
          </select>
        </div>
        <button title="Add Exercise" class="btn btn-primary btn-small addexercise"><i class="fa fa-plus-circle"></i> Add Exercise</button>
      </div>
      <div class="row">
        <input id="order" type="text" style="display: none;" name="order" value="">
        <table id="sort" class="table table-hover">
          <thead>
            <th>Name</th>
            <th>Sets</th>
          </thead>
          <tbody>
            {% for plan in cycle.exercises %}
                {% set outer_loop = loop %}
                <tr class="exercise">
                    <td class="col-xs-3">
                        <select class="form-control exercise" name="exercise-{{ loop.index }}">
                            {{ generate_options(exercises, plan.exercise) }}
                        </select>
                    </td>
                    <td class="col-xs-6">
                        <table class="table table-hover sets">
                            <thead>
                                <th>Repetitions</th>
                                {% if plan.exercise.use_weight %}
                                    <th>Weight (kg)</th>
                                {% endif %}
                                <th><button title="Add Set" class="btn btn-primary btn-xs addset"><i class="fa fa-plus-circle"></i> Add Set</button></th>
                            </thead>
                            <tbody>
                                {% for set in plan.sets %}
                                    <tr>
                                        <td>
                                            <input type="number" class="form-control" value="{{ set.repetitions }}" required name="set-{{ outer_loop.index }}-{{ loop.index }}-reps">
                                        </td>
                                        {% if plan.exercise.use_weight %}
                                            <td>
                                                <input type="number" step="any" class="form-control" value="{{ set.weight }}" required name="set-{{ outer_loop.index }}-{{ loop.index }}-weight">
                                            </td>
                                        {% endif %}
                                        <td><button title="Remove Set" class="btn btn-danger btn-small removeset"><i class="fa fa-trash-o"></i></button><td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </td>
                    <td class="col-xs-4">
                        <button title="Remove Exercise" class="btn btn-danger btn-small removeexercise"><i class="fa fa-trash-o"></i></button>
                    </td>
                </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-xs-offset-2 col-xs-10">
        <button type="submit" class="btn btn-primary">Save</button>
        <a href="{{ url_for('cycles.index') }}" class="btn btn-default">Cancel</a>
    </div>
  </div>
</form>
{% endblock %}

{% block js_footer%}
<script type="text/javascript">
  // Return a helper with preserved width of cells
  var fixHelperModified = function(e, tr) {
      var $originals = tr.children();
      var $helper = tr.clone();
      $helper.children().each(function(index)
      {
        $(this).width($originals.eq(index).width())
      });
      return $helper;
  };

  var sortChangeHandler = function(event, ui) {
    var order = "";
    $("#sort > tbody > tr.exercise").each(function(index, item){
        var ex = $(item).find("select.exercise");
        var name = ex.attr("name");
        var originalPosition = name.split("-")[1];
        order += originalPosition + ",";
    });
    order.slice(0, -1);
    $("#order").val(order);
  };

  $("#sort > tbody").sortable({
    helper: fixHelperModified,
    stop: sortChangeHandler
  }).disableSelection();

  function getNewSetRow(weight, exerciseNumber, setNumber) {
    var columns = '<td><input type="number" class="form-control" required name="set-' + exerciseNumber + '-' + setNumber + '-reps"></td>';
    if (weight) {
      columns += '<td><input type="number" step="any" class="form-control" required name="set-' + exerciseNumber + '-' + setNumber + '-weight"></td>';
    }
    columns += '<td><button title="Remove Set" class="btn btn-danger btn-small removeset"><i class="fa fa-trash-o"></i></button><td>';
    return '<tr>' + columns + '</tr>';
  }

  function getNewExerciseRow(exercises, exerciseNumber) {
    var clonedSelect = exercises.clone().removeAttr("id").attr("name", "exercise-" + exerciseNumber).addClass("exercise");
    var exercise = exercises.find(":selected");
    var weight = exercise.hasClass("weight");

    clonedSelect.find("option").each(function() {
      if ($(this).val() != exercise.val()) {
        $(this).attr("disabled", "disabled");
      } else {
        $(this).attr("selected", "selected");
      }
    });

    var exColumn = '<td class="col-xs-3">'+ $("<div />").append(clonedSelect).html() + '</td>';

    var setColumn = '<td class="col-xs-6"><table class="table table-hover sets"><thead><th>Repetitions</th>';
    if (weight) {
      setColumn += '<th>Weight (kg)</th>';
    }
    setColumn += '<th><button title="Add Set" class="btn btn-primary btn-xs addset"><i class="fa fa-plus-circle"></i> Add Set</button></th></thead><tbody></tbody></table></td>';

    var fillerColumn = '<td class="col-xs-4"><button title="Remove Exercise" class="btn btn-danger btn-small removeexercise"><i class="fa fa-trash-o"></i></button></td>';

    return '<tr class="exercise">' + exColumn + setColumn + fillerColumn + "</tr>";
  }

  $(document).ready(function() {
    var exCount = parseInt($("#excount").text());

    $("#sort").on("click", "button.addset", function(e) {
      e.preventDefault();

      var row = $(this).closest("tr.exercise");
      var setTable = row.find(".sets");
      var setNumber = (setTable.find("tr")).size();

      var exercise = row.find(".exercise");
      var exerciseNumber = exercise.attr("name").split("-")[1];

      var selected = exercise.find(":selected");
      var weight = selected.hasClass("weight");

      var newRow = $(getNewSetRow(weight, exerciseNumber, setNumber));
      newRow.hide();
      setTable.find('tr:last').after(newRow);
      newRow.fadeIn(250);
    });

    $("#sort").on("click", "button.removeset", function(e) {
      e.preventDefault();
      var row = $(this).closest("tr");
      row.fadeOut(250, function() {
        row.remove();
      });
    });

    $(".addexercise").click(function(e) {
      e.preventDefault();
      var exercises = $("select#newexercise");
      // var exercise = exercises.find(":selected");
      // var exerciseNumber = $("table#sort > tbody > tr").size() + 1;
      var exerciseNumber = exCount + 1;
      var newRow = $(getNewExerciseRow(exercises, exerciseNumber));
//      var lastRow = $("table#sort > tbody > tr:last");
//
//      lastRow.after(newRow);
//      newRow.fadeIn(250);
      $("table#sort > tbody").append(newRow).children(':last').hide().fadeIn(250);
      exCount += 1;
      sortChangeHandler(null, null);
    });

    $("#sort").on("click", "button.removeexercise", function(e) {
      e.preventDefault();
      var row = $(this).closest("tr");
      row.fadeOut(250, function() {
        row.remove();
        sortChangeHandler(null, null);
      });
    });
  });
</script>
{% endblock %}

trainingbook/templates/cycles/list.html
{% extends "base.html" %}
{% set active_page = "cycles" %}

{% block page_header %}
    <h1>
        Cycles
        <a href="{{ url_for('cycles.add') }}">
            <button class="btn btn-primary btn-large">
            <i class="fa fa-plus-circle"></i></button>
        </a>
    </h1>
{% endblock %}

{% block content %}
    <table class="table table-hover table-condensed">
        <thead>
            <th>Name</th>
            <th>Exercises</th>
            <th></th>
        </thead>
        <tbody>
            {% for cycle in cycles %}
                <tr>
                    <td>{{ cycle.name }}</td>
                    <td>
                        {% if cycle.exercises %}
                            <ul>
                            {% for exercise in cycle.exercises %}
                                <li>{{ exercise }}</li>
                            {% endfor %}
                            </ul>
                        {% endif %}
                    </td>
                    <td>
                        <a href="{{ url_for('cycles.edit', id=cycle.id) }}">
                            <button class="btn btn-primary"><i class="fa fa-pencil"></i></button>
                        </a>
                        <a class="confirmLink" href="{{ url_for('cycles.delete', id=cycle.id) }}">
                            <button class="btn btn-danger"><i class="fa fa-trash-o"></i></button>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <div id="dialog" title="Confirmation Required">Are you sure about this?</div>
{% endblock %}

{% block js_footer %}
    <script type="text/javascript">
        $(document).ready(function () {
            $("#dialog").dialog({
                autoOpen: false,
                modal: true
            });
        });

        $(".confirmLink").click(function (e) {
            e.preventDefault();
            var targetUrl = $(this).attr("href");

            $("#dialog").dialog({
                buttons: {
                    "Confirm": function () {
                        window.location.href = targetUrl;
                    },
                    "Cancel": function () {
                        $(this).dialog("close");
                    }
                }
            });

            $("#dialog").dialog("open");
        });
    </script>
{% endblock %}

trainingbook/templates/cycles/new_edit.html
{% extends "base.html" %}
{% import 'forms.html' as forms %}

{% block page_header %}
    <h1>Edit Cycle</h1>
{% endblock %}

{% macro generate_options(exercises, selected=None) -%}
    {% for exercise in exercises %}
        <option {% if selected %}{% if selected.id == exercise.id %}selected="selected"{% else %}disabled="disabled"{% endif %}{% endif %}
                value="{{ exercise.id }}" {% if exercise.use_weight %}class="weight"{% endif %}>{{ exercise.name }}</option>
    {% endfor %}
{% endmacro %}

{% block content %}
<div style="display: none;" id="excount">{{ cycle.exercises|count }}</div>
<form class="form-horizontal" role="form" method="post">
  <div class="form-group">
    <label for="inputName" class="col-xs-2 control-label">Name</label>
    <div class="col-xs-10">
      <input type="text" class="form-control" id="inputName" name="name" placeholder="Enter Name" value="{{ cycle.name }}" required>
    </div>
  </div>
  <div class="form-group">
    <label for="inputExercises" class="col-xs-2 control-label">Exercises</label>
    <div class="col-xs-10">
      <!-- show some kind of table here -->
      <div class="row">
        <div class="col-xs-3">
          <select id="newexercise" class="form-control">
            {{ generate_options(exercises) }}
          </select>
        </div>
        <button title="Add Exercise" class="btn btn-primary btn-small addexercise"><i class="fa fa-plus-circle"></i> Add Exercise</button>
      </div>
      <div class="row">
        <input id="order" type="text" style="display: none;" name="order" value="">
        <table id="sort" class="table table-hover">
          <thead>
            <th>Name</th>
            <th>Sets</th>
          </thead>
          <tbody>
            {% for plan in cycle.exercises %}
                {% set outer_loop = loop %}
                <tr class="exercise">
                    <td class="col-xs-3">
                        <select class="form-control exercise" name="exercise-{{ loop.index }}">
                            {{ generate_options(exercises, plan.exercise) }}
                        </select>
                    </td>
                    <td class="col-xs-6">
                        <table class="table table-hover sets">
                            <thead>
                                <th>Repetitions</th>
                                {% if plan.exercise.use_weight %}
                                    <th>Weight (kg)</th>
                                {% endif %}
                                <th><button title="Add Set" class="btn btn-primary btn-xs addset"><i class="fa fa-plus-circle"></i> Add Set</button></th>
                            </thead>
                            <tbody>
                                {% for set in plan.sets %}
                                    <tr>
                                        <td>
                                            <input type="number" class="form-control" value="{{ set.repetitions }}" required name="set-{{ outer_loop.index }}-{{ loop.index }}-reps">
                                        </td>
                                        {% if plan.exercise.use_weight %}
                                            <td>
                                                <input type="number" step="any" class="form-control" value="{{ set.weight }}" required name="set-{{ outer_loop.index }}-{{ loop.index }}-weight">
                                            </td>
                                        {% endif %}
                                        <td><button title="Remove Set" class="btn btn-danger btn-small removeset"><i class="fa fa-trash-o"></i></button><td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </td>
                    <td class="col-xs-4">
                        <button title="Remove Exercise" class="btn btn-danger btn-small removeexercise"><i class="fa fa-trash-o"></i></button>
                    </td>
                </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-xs-offset-2 col-xs-10">
        <button type="submit" class="btn btn-primary">Save</button>
        <a href="{{ url_for('cycles.index') }}" class="btn btn-default">Cancel</a>
    </div>
  </div>
</form>
{% endblock %}

{% block js_footer%}
<script type="text/javascript">
  // Return a helper with preserved width of cells
  var fixHelperModified = function(e, tr) {
      var $originals = tr.children();
      var $helper = tr.clone();
      $helper.children().each(function(index)
      {
        $(this).width($originals.eq(index).width())
      });
      return $helper;
  };

  var sortChangeHandler = function(event, ui) {
    var order = "";
    $("#sort > tbody > tr.exercise").each(function(index, item){
        var ex = $(item).find("select.exercise");
        var name = ex.attr("name");
        var originalPosition = name.split("-")[1];
        order += originalPosition + ",";
    });
    order.slice(0, -1);
    $("#order").val(order);
  };

  $("#sort > tbody").sortable({
    helper: fixHelperModified,
    stop: sortChangeHandler
  }).disableSelection();

  function getNewSetRow(weight, exerciseNumber, setNumber) {
    var columns = '<td><input type="number" class="form-control" required name="set-' + exerciseNumber + '-' + setNumber + '-reps"></td>';
    if (weight) {
      columns += '<td><input type="number" step="any" class="form-control" required name="set-' + exerciseNumber + '-' + setNumber + '-weight"></td>';
    }
    columns += '<td><button title="Remove Set" class="btn btn-danger btn-small removeset"><i class="fa fa-trash-o"></i></button><td>';
    return '<tr>' + columns + '</tr>';
  }

  function getNewExerciseRow(exercises, exerciseNumber) {
    var clonedSelect = exercises.clone().removeAttr("id").attr("name", "exercise-" + exerciseNumber).addClass("exercise");
    var exercise = exercises.find(":selected");
    var weight = exercise.hasClass("weight");

    clonedSelect.find("option").each(function() {
      if ($(this).val() != exercise.val()) {
        $(this).attr("disabled", "disabled");
      } else {
        $(this).attr("selected", "selected");
      }
    });

    var exColumn = '<td class="col-xs-3">'+ $("<div />").append(clonedSelect).html() + '</td>';

    var setColumn = '<td class="col-xs-6"><table class="table table-hover sets"><thead><th>Repetitions</th>';
    if (weight) {
      setColumn += '<th>Weight (kg)</th>';
    }
    setColumn += '<th><button title="Add Set" class="btn btn-primary btn-xs addset"><i class="fa fa-plus-circle"></i> Add Set</button></th></thead><tbody></tbody></table></td>';

    var fillerColumn = '<td class="col-xs-4"><button title="Remove Exercise" class="btn btn-danger btn-small removeexercise"><i class="fa fa-trash-o"></i></button></td>';

    return '<tr class="exercise">' + exColumn + setColumn + fillerColumn + "</tr>";
  }

  $(document).ready(function() {
    var exCount = parseInt($("#excount").text());

    $("#sort").on("click", "button.addset", function(e) {
      e.preventDefault();

      var row = $(this).closest("tr.exercise");
      var setTable = row.find(".sets");
      var setNumber = (setTable.find("tr")).size();

      var exercise = row.find(".exercise");
      var exerciseNumber = exercise.attr("name").split("-")[1];

      var selected = exercise.find(":selected");
      var weight = selected.hasClass("weight");

      var newRow = $(getNewSetRow(weight, exerciseNumber, setNumber));
      newRow.hide();
      setTable.find('tr:last').after(newRow);
      newRow.fadeIn(250);
    });

    $("#sort").on("click", "button.removeset", function(e) {
      e.preventDefault();
      var row = $(this).closest("tr");
      row.fadeOut(250, function() {
        row.remove();
      });
    });

    $(".addexercise").click(function(e) {
      e.preventDefault();
      var exercises = $("select#newexercise");
      // var exercise = exercises.find(":selected");
      // var exerciseNumber = $("table#sort > tbody > tr").size() + 1;
      var exerciseNumber = exCount + 1;
      var newRow = $(getNewExerciseRow(exercises, exerciseNumber));
      var lastRow = $("table#sort > tbody > tr:last");

      lastRow.after(newRow);
      newRow.fadeIn(250);
      exCount += 1;
      sortChangeHandler(null, null);
    });

    $("#sort").on("click", "button.removeexercise", function(e) {
      e.preventDefault();
      var row = $(this).closest("tr");
      row.fadeOut(250, function() {
        row.remove();
        sortChangeHandler(null, null);
      });
    });
  });
</script>
{% endblock %}